S = lambda value: value.split("|")

GENRES = S(
    "Action|Adventure|Building Game|Economic Simulation|Fighting Game|First-Person Shooter|Interactive Movie|Platformer|Puzzle Game|Racing|Real-Time Strategy|Role-Playing Game|Simulation|Skill Game|Sports Game|Strategy|Survival Game|Third-Person Shooter|Visual Novel|Battle Royale|Extraction Shooter|Survivors-like|Roguelike|Roguelite|Deckbuilder|Automation|Cozy Game|Social Deduction|Immersive Sim|Soulslike|Metroidvania"
)

_GENRE_PROFILES = {
    "Action": (["Teenagers", "Adults"], (10, 40, 30, 20)),
    "Adventure": (["Adults", "Seniors"], (40, 30, 15, 15)),
    "Building Game": (["Adults", "Seniors"], (30, 20, 20, 30)),
    "Economic Simulation": (["Adults", "Seniors"], (50, 20, 10, 20)),
    "Fighting Game": (["Teenagers", "Adults"], (20, 20, 10, 50)),
    "First-Person Shooter": (["Teenagers", "Adults"], (10, 50, 20, 20)),
    "Interactive Movie": (["Teenagers", "Adults", "Seniors"], (10, 50, 30, 10)),
    "Platformer": (["Children", "Teenagers"], (25, 25, 25, 25)),
    "Puzzle Game": (["Teenagers", "Adults", "Seniors"], (50, 10, 10, 30)),
    "Racing": (["Children", "Teenagers", "Adults", "Seniors", "All"], (10, 40, 30, 20)),
    "Real-Time Strategy": (["Teenagers", "Adults"], (30, 30, 10, 30)),
    "Role-Playing Game": (["Adults", "Seniors"], (40, 30, 15, 15)),
    "Simulation": (["Teenagers", "Adults"], (10, 40, 20, 30)),
    "Skill Game": (["Children", "Teenagers", "Adults", "Seniors", "All"], (40, 10, 10, 40)),
    "Sports Game": (["Children", "Teenagers", "Adults"], (20, 30, 10, 40)),
    "Strategy": (["Adults", "Seniors"], (50, 10, 10, 30)),
    "Survival Game": (["Teenagers", "Adults", "Seniors"], (30, 30, 10, 30)),
    "Third-Person Shooter": (["Teenagers", "Adults"], (20, 40, 20, 20)),
    "Visual Novel": (["Children", "Teenagers", "Adults", "Seniors", "All"], (40, 40, 10, 10)),
    "Battle Royale": (["Teenagers", "Adults"], (28, 24, 8, 40)),
    "Extraction Shooter": (["Adults"], (32, 18, 10, 40)),
    "Survivors-like": (["Teenagers", "Adults"], (48, 18, 8, 26)),
    "Roguelike": (["Adults", "Seniors"], (54, 12, 8, 26)),
    "Roguelite": (["Teenagers", "Adults"], (46, 20, 10, 24)),
    "Deckbuilder": (["Teenagers", "Adults", "Seniors"], (58, 16, 8, 18)),
    "Automation": (["Adults", "Seniors"], (44, 14, 6, 36)),
    "Cozy Game": (["Children", "Teenagers", "Adults"], (42, 32, 16, 10)),
    "Social Deduction": (["Teenagers", "Adults"], (52, 16, 14, 18)),
    "Immersive Sim": (["Adults"], (44, 18, 10, 28)),
    "Soulslike": (["Teenagers", "Adults"], (42, 28, 10, 20)),
    "Metroidvania": (["Teenagers", "Adults"], (40, 30, 12, 18)),
}

GENRE_PROFILES = {name: {"targets": targets, "priorities": priorities} for name, (targets, priorities) in _GENRE_PROFILES.items()}

TOPICS = S(
    "Agents|Agriculture|Airplanes|Aliens|American Football|Ancient|Ancient China|Ancient Egypt|Androids|Angels|Animals|Anime|Ants|Apocalypse|Archaeology|Archery|Art|Assassins|Asteroids|Astronauts|Athletics|Atlantis|Aztecs|Barbarians|Bards|Baseball|Basketball|Bicycle|Billiards|Birds|Books|Bounty Hunter|Bowling|Boxing|Building Blocks|Bunker|Cabs|Candy|Cars|Casinos|Castles|Cats|Chemistry|Chess|Chickens|Cinema|Circus|Cities|Civilizations|Cleaning|Climbing|Colonization|Comedy|Companies|Conquest|Conspiracies|Contract Killer|Cooking|Court Case|Cowboys|Crafting|Cricket|Crime|Crocodiles|Curling|Curses|Cyberpunk|Cyberspace|Cyborgs|Dancing|Darts|Dating|Deck Building|Demons|Desert|Detective|Devils|Dice Games|Dieselpunk|Digging|Dinosaurs|Diplomacy|Diving|Doctors|Dogs|Dolls|Dolphins|Dragons|Drawing|Dreams|Drones|Druids|Dungeons|Dwarfs|Economy|Education|Elements|Elves|End Times|Erotica|Espionage|Everyday Life|Evolution|Expeditions|Extreme Sports|Factories|Fairies|Fantasy|Fashion|Fencing|Fire Department|Fish|Fishing|Fitness|Food|Frogs|Fruit|Gambling|Game Development|Gangsters|Genetics|Ghosts|Gladiators|Goats|Goblins|Gods|Golf|Graveyards|Greek Mythology|Hacking|Handball|Healthcare|Hedgehogs|Helicopters|Hell|Hiking|Historical|Horror|Horses|Hospital|Hotels|Hunting|Ice Age|Ice Hockey|Inca|Industrialization|Insects|Islands|Jet Ski|Jungle|Karate|Kart Racing|Kickboxing|Kids|Knights|Kung Fu|Labyrinth|Languages|Learning|Machines|Mafia|Magic|Makeup|Martial Arts|Mathematics|Mecha|Mercenary|Mermaids|Middle Ages|Military|Mining|Monkeys|Monster|Motorcycles|Motorsports|Mountaineering|Movies|Mummies|Mushrooms|Music|Musical Instrument|Mutants|Nature|Ninjas|Noble Houses|Oceans|Octopus|Orcs|Paintball|Parallel Worlds|Parkour|Parlor Games|Parties|Pharaohs|Photography|Physics|Pinball|Pirates|Planets|Plants|Playing Cards|Plumber|Police|Politics|Portals|Predators|Prison|Puzzles|Quiz Show|Rabbits|Radioactivity|Rallycross|Raw Materials|Recycling|Religion|Renovation|Reporters|Restaurants|Revolution|Riding|Robots|Rockstars|Roman Empire|Romance|Romans|Rugby|Saboteurs|Sailing|Samurai|Sandbox|School|Science|Secret Society|Sewers|Sheep|Ships|Showbiz|Singing|Skateboards|Skeletons|Skiing|Skydiving|Snowboarding|Soccer|Space|Space Stations|Spaceships|Special Forces|Spiders|Sports|Squash|Squirrels|Steampunk|Stock Car|Stock Exchanges|Stone Age|Stones|Stuffed Animals|Submarines|Super Villains|Superheroes|Surfing|Survivalism|Swimming|Table Tennis|Tanks|Television|Tennis|Terraforming|Theme Parks|Thieves|Time Travel|Tourism|Toys|Trains|Transportation|Treasure|Treasure Hunters|Trolls|Trucks|Tubes|UFOs|University|Vacation|Vampires|Victorian Age|Vikings|Villages|Viruses|Viticulture|Volleyball|Werewolves|Wild West|Witches|Wizards|World Wars|Worms|Wrestling|Yakuza|Zeppelins|Zombies|Zoo|Pets"
)

GOOD_MATCHES = {
    "Action": set(S("Agents|Airplanes|Aliens|Ancient|Ancient China|Ancient Egypt|Androids|Angels|Animals|Anime|Ants|Apocalypse|Archery|Assassins|Asteroids|Astronauts|Atlantis|Aztecs|Barbarians|Bards|Bounty Hunter|Boxing|Bunker|Castles|Climbing|Comedy|Conquest|Conspiracies|Contract Killer|Cowboys|Crime|Crocodiles|Cyberpunk|Cyberspace|Cyborgs|Demons|Desert|Detective|Devils|Dieselpunk|Digging|Dinosaurs|Diving|Dolphins|Dragons|Drones|Dungeons|Dwarfs|Elves|End Times|Espionage|Fantasy|Fencing|Fire Department|Gangsters|Ghosts|Gladiators|Goblins|Gods|Graveyards|Greek Mythology|Helicopters|Hell|Historical|Horror|Hunting|Ice Age|Inca|Insects|Jungle|Karate|Kickboxing|Knights|Kung Fu|Mafia|Magic|Martial Arts|Mecha|Mercenary|Middle Ages|Military|Monkeys|Monster|Mountaineering|Mummies|Mutants|Ninjas|Oceans|Orcs|Paintball|Parallel Worlds|Parkour|Pirates|Planets|Plants|Police|Portals|Predators|Prison|Puzzles|Radioactivity|Revolution|Robots|Roman Empire|Romans|Saboteurs|Samurai|Sewers|Skeletons|Skydiving|Space|Space Stations|Spaceships|Special Forces|Spiders|Squirrels|Steampunk|Stone Age|Stones|Submarines|Super Villains|Superheroes|Survivalism|Tanks|Thieves|Time Travel|Treasure|Treasure Hunters|Trolls|UFOs|Vampires|Vikings|Viruses|Werewolves|Wild West|Witches|Wizards|World Wars|Worms|Wrestling|Yakuza|Zeppelins|Zombies|Pets")),
    "Adventure": set(S("Agents|Ancient|Ancient Egypt|Androids|Angels|Anime|Apocalypse|Archaeology|Astronauts|Aztecs|Bards|Circus|Comedy|Court Case|Crime|Curses|Cyberpunk|Cyborgs|Dating|Deck Building|Demons|Desert|Detective|Devils|Dieselpunk|Dragons|Dreams|Druids|Dungeons|Dwarfs|Elves|End Times|Erotica|Everyday Life|Expeditions|Fairies|Fantasy|Fencing|Ghosts|Goblins|Gods|Graveyards|Greek Mythology|Hell|Hiking|Historical|Horror|Ice Age|Inca|Islands|Jungle|Kids|Knights|Labyrinth|Magic|Mermaids|Middle Ages|Monkeys|Monster|Mummies|Noble Houses|Orcs|Parallel Worlds|Pharaohs|Photography|Pirates|Planets|Police|Radioactivity|Religion|Reporters|Roman Empire|Romance|Romans|Saboteurs|Secret Society|Sewers|Skeletons|Space|Steampunk|Stone Age|Super Villains|Thieves|Time Travel|Treasure|Treasure Hunters|Trolls|University|Vampires|Victorian Age|Vikings|Werewolves|Wild West|Witches|Wizards|World Wars")),
    "Building Game": set(S("Agriculture|Ancient|Ancient China|Ancient Egypt|Animals|Ants|Apocalypse|Atlantis|Aztecs|Barbarians|Building Blocks|Casinos|Castles|Cinema|Circus|Cities|Civilizations|Companies|Conquest|Cooking|Cowboys|Crafting|Crime|Desert|Digging|Diplomacy|Doctors|Dungeons|Dwarfs|Economy|Education|Elves|End Times|Evolution|Expeditions|Factories|Fitness|Goblins|Gods|Graveyards|Greek Mythology|Healthcare|Hell|Hospital|Hotels|Ice Age|Inca|Industrialization|Insects|Islands|Jungle|Knights|Learning|Magic|Middle Ages|Mining|Monster|Nature|Noble Houses|Oceans|Orcs|Parlor Games|Pharaohs|Pirates|Planets|Plants|Police|Prison|Radioactivity|Raw Materials|Recycling|Renovation|Restaurants|Roman Empire|Romans|Sandbox|School|Ships|Showbiz|Space|Space Stations|Stone Age|Stones|Survivalism|Television|Terraforming|Theme Parks|Tourism|Trains|Transportation|Treasure|Trucks|University|Vacation|Vikings|Villages|Viticulture|Wild West|World Wars|Zombies|Zoo")),
    "Economic Simulation": set(S("Agriculture|American Football|Ancient|Animals|Art|Athletics|Baseball|Basketball|Bicycle|Boxing|Cabs|Candy|Cars|Casinos|Castles|Cinema|Circus|Cities|Civilizations|Colonization|Companies|Conquest|Cooking|Crafting|Cricket|Crime|Curling|Digging|Diplomacy|Doctors|Dungeons|Economy|Education|End Times|Erotica|Everyday Life|Factories|Fashion|Fire Department|Fish|Fitness|Food|Gambling|Game Development|Gangsters|Gladiators|Golf|Handball|Healthcare|Hell|Historical|Horses|Hospital|Hotels|Ice Age|Ice Hockey|Industrialization|Islands|Kart Racing|Kickboxing|Knights|Kung Fu|Learning|Machines|Mafia|Makeup|Mathematics|Middle Ages|Mining|Motorcycles|Motorsports|Movies|Music|Nature|Noble Houses|Parties|Pharaohs|Pirates|Planets|Police|Politics|Prison|Rallycross|Raw Materials|Recycling|Renovation|Restaurants|Riding|Rockstars|Roman Empire|Romans|Rugby|Sandbox|School|Science|Ships|Showbiz|Singing|Soccer|Space|Sports|Squash|Steampunk|Stock Car|Stock Exchanges|Super Villains|Table Tennis|Television|Tennis|Theme Parks|Thieves|Tourism|Trains|Transportation|Treasure|Trucks|University|Vacation|Victorian Age|Villages|Viticulture|Volleyball|Wild West|Wrestling|Yakuza|Zeppelins|Zoo")),
    "Fighting Game": set(S("Ancient China|Androids|Animals|Assassins|Barbarians|Boxing|Contract Killer|Cyberpunk|Cyborgs|Demons|Dinosaurs|Fantasy|Fencing|Fire Department|Fitness|Gladiators|Goblins|Gods|Karate|Kickboxing|Kung Fu|Martial Arts|Mecha|Monster|Mutants|Ninjas|Orcs|Predators|Robots|Roman Empire|Samurai|Skeletons|Space|Sports|Superheroes|Trolls|Vikings|Werewolves|Wrestling|Yakuza|Pets")),
    "First-Person Shooter": set(S("Agents|Aliens|Ancient|Ancient Egypt|Androids|Angels|Apocalypse|Archery|Assassins|Aztecs|Barbarians|Bounty Hunter|Boxing|Bunker|Castles|Climbing|Conspiracies|Contract Killer|Cowboys|Crime|Cyberpunk|Cyberspace|Cyborgs|Demons|Desert|Detective|Devils|Dinosaurs|Dragons|Druids|Dungeons|Dwarfs|Elves|End Times|Espionage|Fantasy|Fencing|Gangsters|Ghosts|Gladiators|Goblins|Gods|Graveyards|Greek Mythology|Helicopters|Hell|Historical|Horror|Hunting|Ice Age|Inca|Insects|Jungle|Karate|Knights|Mafia|Magic|Martial Arts|Mecha|Mercenary|Middle Ages|Military|Monster|Mountaineering|Mummies|Mutants|Ninjas|Oceans|Orcs|Parallel Worlds|Parkour|Pharaohs|Physics|Police|Portals|Predators|Prison|Puzzles|Radioactivity|Revolution|Riding|Robots|Roman Empire|Romans|Saboteurs|Samurai|Sandbox|Secret Society|Sewers|Skeletons|Skydiving|Space|Space Stations|Spaceships|Special Forces|Spiders|Steampunk|Stone Age|Submarines|Super Villains|Superheroes|Survivalism|Tanks|Thieves|Time Travel|Treasure Hunters|Trolls|UFOs|Vampires|Vikings|Werewolves|Wild West|Witches|Wizards|World Wars|Yakuza|Zombies")),
    "Interactive Movie": set(S("Agents|Aliens|Androids|Angels|Anime|Apocalypse|Bounty Hunter|Comedy|Conspiracies|Contract Killer|Court Case|Cowboys|Crime|Curses|Cyberpunk|Cyberspace|Cyborgs|Dancing|Dating|Demons|Detective|Dragons|End Times|Erotica|Espionage|Everyday Life|Fantasy|Gangsters|Ghosts|Hacking|Horror|Kids|Knights|Mafia|Mermaids|Military|Movies|Music|Ninjas|Noble Houses|Parallel Worlds|Photography|Prison|Reporters|Revolution|Robots|Romance|Saboteurs|Samurai|Skeletons|Spaceships|Super Villains|Superheroes|Time Travel|UFOs|University|Vampires|Werewolves|Wild West|Witches|Wizards|World Wars")),
    "Platformer": set(S("Agents|Ancient|Ancient China|Ancient Egypt|Androids|Angels|Animals|Anime|Ants|Archery|Assassins|Atlantis|Aztecs|Barbarians|Bards|Birds|Boxing|Building Blocks|Candy|Castles|Cats|Chickens|Climbing|Comedy|Contract Killer|Cowboys|Crocodiles|Cyberpunk|Cyberspace|Cyborgs|Dancing|Demons|Detective|Devils|Digging|Dinosaurs|Dogs|Dolls|Dragons|Drawing|Dreams|Druids|Dungeons|Dwarfs|Elements|Elves|End Times|Espionage|Everyday Life|Evolution|Extreme Sports|Fairies|Fantasy|Fencing|Fire Department|Fish|Fitness|Frogs|Fruit|Gangsters|Ghosts|Gladiators|Goats|Goblins|Gods|Graveyards|Greek Mythology|Hedgehogs|Hell|Hiking|Horror|Horses|Hunting|Ice Age|Inca|Insects|Islands|Jungle|Karate|Kickboxing|Kids|Knights|Kung Fu|Magic|Martial Arts|Mercenary|Mermaids|Middle Ages|Monkeys|Monster|Mountaineering|Mummies|Mushrooms|Music|Mutants|Ninjas|Octopus|Orcs|Paintball|Parallel Worlds|Parkour|Pharaohs|Pinball|Pirates|Plants|Plumber|Police|Portals|Predators|Prison|Puzzles|Rabbits|Reporters|Revolution|Riding|Robots|Roman Empire|Romans|Saboteurs|Samurai|School|Sewers|Sheep|Skateboards|Skeletons|Skiing|Skydiving|Space|Space Stations|Spaceships|Special Forces|Spiders|Squirrels|Steampunk|Stone Age|Stones|Stuffed Animals|Super Villains|Superheroes|Survivalism|Thieves|Time Travel|Toys|Treasure|Treasure Hunters|Trolls|Tubes|Vampires|Vikings|Werewolves|Wild West|Witches|Wizards|World Wars|Zombies|Pets")),
    "Puzzle Game": set(S("Agriculture|Ancient|Ancient China|Animals|Archaeology|Art|Books|Building Blocks|Candy|Casinos|Chemistry|Circus|Cities|Conspiracies|Cooking|Crafting|Cyberpunk|Cyberspace|Dancing|Dating|Deck Building|Detective|Dice Games|Dieselpunk|Digging|Diving|Dragons|Drawing|Dreams|Education|Elements|Erotica|Espionage|Everyday Life|Evolution|Expeditions|Fairies|Fantasy|Fashion|Fish|Fitness|Food|Fruit|Gambling|Genetics|Ghosts|Goblins|Greek Mythology|Hacking|Hiking|Horror|Hospital|Kids|Labyrinth|Languages|Learning|Magic|Mathematics|Middle Ages|Mining|Movies|Mummies|Music|Nature|Octopus|Parallel Worlds|Parlor Games|Pharaohs|Photography|Physics|Planets|Plants|Playing Cards|Plumber|Portals|Prison|Puzzles|Quiz Show|Recycling|Rockstars|Romans|School|Science|Ships|Singing|Snowboarding|Space|Steampunk|Stone Age|Stones|Television|Terraforming|Theme Parks|Time Travel|Toys|Trains|Transportation|Treasure|Tubes|Victorian Age|Villages|Viruses|Wizards|Worms|Zoo|Pets")),
    "Racing": set(S("Airplanes|Bicycle|Cabs|Cars|Desert|Drones|Economy|Extreme Sports|Historical|Horses|Jet Ski|Kart Racing|Motorcycles|Motorsports|Physics|Police|Rallycross|Riding|Roman Empire|Sailing|Skateboards|Skiing|Skydiving|Spaceships|Sports|Stock Car|Surfing|Transportation|Trucks")),
    "Real-Time Strategy": set(S("Aliens|Ancient|Ancient China|Ancient Egypt|Androids|Animals|Ants|Apocalypse|Atlantis|Aztecs|Bunker|Castles|Cities|Civilizations|Colonization|Companies|Conquest|Cowboys|Cyborgs|Deck Building|Demons|Desert|Dieselpunk|Dinosaurs|Diplomacy|Dragons|Drones|Druids|Dungeons|Dwarfs|Economy|Elves|End Times|Espionage|Factories|Fantasy|Fencing|Fire Department|Goblins|Gods|Greek Mythology|Helicopters|Historical|Ice Age|Inca|Industrialization|Insects|Jungle|Knights|Magic|Martial Arts|Mecha|Mercenary|Middle Ages|Military|Mining|Mutants|Noble Houses|Oceans|Orcs|Pharaohs|Planets|Plants|Police|Radioactivity|Raw Materials|Robots|Roman Empire|Romans|Saboteurs|Sailing|Samurai|Science|Ships|Space|Space Stations|Spaceships|Special Forces|Steampunk|Stone Age|Submarines|Tanks|Terraforming|Trains|Transportation|Trolls|UFOs|Victorian Age|Vikings|Villages|Wild West|Wizards|World Wars|Zeppelins")),
    "Role-Playing Game": set(S("Ancient|Ancient China|Androids|Angels|Anime|Apocalypse|Barbarians|Bards|Castles|Curses|Cyberpunk|Cyborgs|Deck Building|Demons|Devils|Dragons|Druids|Dungeons|Dwarfs|Elves|End Times|Fairies|Fantasy|Fencing|Ghosts|Goblins|Gods|Graveyards|Greek Mythology|Hell|Hunting|Islands|Knights|Labyrinth|Magic|Martial Arts|Middle Ages|Monster|Mutants|Noble Houses|Orcs|Parallel Worlds|Pirates|Planets|Radioactivity|Romans|Samurai|Sandbox|Secret Society|Skeletons|Space|Space Stations|Spiders|Steampunk|Thieves|Time Travel|Treasure|Treasure Hunters|Trolls|Vampires|Vikings|Werewolves|Witches|Wizards")),
    "Simulation": set(S("Agriculture|Airplanes|Animals|Archery|Asteroids|Astronauts|Bicycle|Cabs|Cars|Casinos|Cities|Cleaning|Climbing|Companies|Cooking|Crafting|Desert|Doctors|Dolphins|Drones|Evolution|Extreme Sports|Fire Department|Fish|Fishing|Gambling|Graveyards|Healthcare|Helicopters|Hiking|Historical|Horses|Hotels|Hunting|Insects|Jet Ski|Kart Racing|Mecha|Mercenary|Military|Mining|Motorcycles|Motorsports|Mountaineering|Nature|Paintball|Photography|Pinball|Planets|Police|Politics|Predators|Rallycross|Recycling|Renovation|Restaurants|Robots|Sailing|Sandbox|Sewers|Ships|Skateboards|Skiing|Skydiving|Snowboarding|Soccer|Space|Space Stations|Spaceships|Sports|Stock Car|Submarines|Surfing|Survivalism|Swimming|Tanks|Terraforming|Theme Parks|Trains|Transportation|Trucks|UFOs|Vacation|Viticulture|World Wars|Wrestling|Zeppelins|Zoo")),
    "Skill Game": set(S("Agriculture|Ancient|Ancient Egypt|Animals|Ants|Archaeology|Archery|Art|Asteroids|Athletics|Baseball|Basketball|Billiards|Birds|Bowling|Building Blocks|Candy|Cars|Casinos|Cats|Chemistry|Chess|Chickens|Circus|Cities|Cleaning|Climbing|Cooking|Crafting|Curling|Cyberpunk|Cyberspace|Dancing|Darts|Deck Building|Dice Games|Dieselpunk|Digging|Diving|Dogs|Dolphins|Dragons|Drawing|Dreams|Education|Elements|Espionage|Everyday Life|Evolution|Expeditions|Factories|Fairies|Fantasy|Fashion|Fencing|Fish|Fishing|Fitness|Food|Frogs|Fruit|Gambling|Genetics|Ghosts|Goats|Goblins|Greek Mythology|Hacking|Handball|Healthcare|Hedgehogs|Hospital|Insects|Jet Ski|Kids|Labyrinth|Languages|Learning|Machines|Magic|Makeup|Mathematics|Middle Ages|Mining|Mountaineering|Movies|Mummies|Mushrooms|Music|Musical Instrument|Nature|Oceans|Octopus|Orcs|Parallel Worlds|Parkour|Parlor Games|Parties|Pharaohs|Physics|Pinball|Planets|Plants|Playing Cards|Plumber|Portals|Prison|Puzzles|Quiz Show|Rabbits|Recycling|Renovation|Riding|Rockstars|Sailing|School|Science|Sheep|Singing|Skateboards|Skiing|Skydiving|Soccer|Space|Spiders|Sports|Squash|Steampunk|Stone Age|Stones|Stuffed Animals|Surfing|Swimming|Table Tennis|Tennis|Theme Parks|Thieves|Time Travel|Toys|Trains|Transportation|Treasure|Tubes|Viruses|Volleyball|Wizards|Worms|Zoo|Pets")),
    "Sports Game": set(S("Airplanes|American Football|Ancient|Animals|Archery|Athletics|Baseball|Basketball|Bicycle|Billiards|Bowling|Boxing|Cars|Climbing|Companies|Cricket|Curling|Cyborgs|Dancing|Darts|Desert|Diving|Economy|Extreme Sports|Fencing|Fish|Fishing|Fitness|Gladiators|Golf|Handball|Hiking|Historical|Horses|Ice Hockey|Jet Ski|Karate|Kart Racing|Kickboxing|Kids|Knights|Kung Fu|Martial Arts|Motorcycles|Motorsports|Mountaineering|Oceans|Orcs|Paintball|Parkour|Rallycross|Romans|Rugby|Sailing|Ships|Skateboards|Skiing|Skydiving|Snowboarding|Soccer|Space Stations|Sports|Squash|Stock Car|Surfing|Swimming|Table Tennis|Tennis|Trucks|Vacation|Volleyball|Wrestling")),
    "Strategy": set(S("Agriculture|Airplanes|Aliens|Ancient|Ancient China|Ancient Egypt|Androids|Apocalypse|Barbarians|Building Blocks|Bunker|Castles|Chemistry|Chess|Cinema|Cities|Civilizations|Colonization|Companies|Conquest|Cooking|Crafting|Crime|Deck Building|Desert|Dice Games|Dieselpunk|Digging|Diplomacy|Dragons|Dwarfs|Economy|Education|Elements|End Times|Espionage|Everyday Life|Evolution|Expeditions|Factories|Fantasy|Fire Department|Food|Gambling|Game Development|Gangsters|Gladiators|Goblins|Greek Mythology|Healthcare|Historical|Hospital|Industrialization|Jungle|Knights|Mafia|Magic|Mecha|Mercenary|Middle Ages|Military|Mining|Mutants|Nature|Noble Houses|Oceans|Parlor Games|Pharaohs|Physics|Planets|Playing Cards|Police|Politics|Radioactivity|Raw Materials|Renovation|Revolution|Robots|Roman Empire|Romans|Saboteurs|Sailing|Science|Space|Space Stations|Spaceships|Special Forces|Steampunk|Stones|Submarines|Tanks|Television|Terraforming|Theme Parks|Trains|Transportation|Trucks|UFOs|Vacation|Victorian Age|Vikings|Villages|Wild West|Wizards|World Wars|Zeppelins|Zoo")),
    "Survival Game": set(S("Agriculture|Aliens|Animals|Apocalypse|Archery|Astronauts|Bunker|Cities|Crafting|Demons|Desert|Digging|Dinosaurs|Diving|Dungeons|End Times|Expeditions|Fishing|Food|Hiking|Horror|Hunting|Ice Age|Islands|Jungle|Middle Ages|Military|Monster|Mutants|Nature|Oceans|Parallel Worlds|Predators|Radioactivity|Raw Materials|Robots|Sandbox|Space|Stone Age|Survivalism|Terraforming|Vampires|Vikings|Viruses|Werewolves|Zombies")),
    "Third-Person Shooter": set(S("Agents|Aliens|Ancient|Ancient China|Ancient Egypt|Androids|Angels|Apocalypse|Archery|Assassins|Atlantis|Aztecs|Barbarians|Bards|Bounty Hunter|Boxing|Bunker|Castles|Climbing|Conquest|Conspiracies|Contract Killer|Cowboys|Crime|Cyberpunk|Cyberspace|Cyborgs|Demons|Desert|Detective|Devils|Dieselpunk|Dinosaurs|Dragons|Druids|Dungeons|Dwarfs|Elves|End Times|Espionage|Fantasy|Fencing|Fruit|Gangsters|Ghosts|Goblins|Gods|Graveyards|Greek Mythology|Helicopters|Hell|Hiking|Historical|Horror|Ice Age|Inca|Insects|Jungle|Karate|Knights|Mafia|Magic|Martial Arts|Mecha|Mercenary|Middle Ages|Monster|Mummies|Mutants|Ninjas|Oceans|Orcs|Parallel Worlds|Parkour|Pharaohs|Physics|Police|Portals|Predators|Prison|Puzzles|Radioactivity|Revolution|Riding|Robots|Roman Empire|Romans|Saboteurs|Sailing|Samurai|Sandbox|Secret Society|Sewers|Skeletons|Skydiving|Space|Space Stations|Spaceships|Special Forces|Spiders|Steampunk|Stone Age|Submarines|Super Villains|Superheroes|Survivalism|Tanks|Thieves|Time Travel|Treasure Hunters|Trolls|UFOs|Vampires|Vikings|Werewolves|Wild West|Witches|Wizards|World Wars|Yakuza|Zombies|Pets")),
    "Visual Novel": set(S("Androids|Angels|Anime|Art|Assassins|Birds|Books|Cats|Chickens|Comedy|Conspiracies|Contract Killer|Court Case|Cowboys|Curses|Cyberpunk|Dancing|Dating|Demons|Detective|Doctors|Dogs|Dragons|Drawing|Elves|Erotica|Everyday Life|Fairies|Fantasy|Fashion|Ghosts|Gladiators|Goats|Horror|Hospital|Hunting|Kids|Magic|Makeup|Mermaids|Middle Ages|Military|Mountaineering|Movies|Music|Ninjas|Noble Houses|Parties|Photography|Politics|Rabbits|Reporters|Romance|Samurai|School|Secret Society|Sheep|Showbiz|Singing|Steampunk|Stuffed Animals|Super Villains|Superheroes|Theme Parks|Thieves|Toys|Treasure|University|Werewolves|Wild West|World Wars|Zombies|Zoo|Pets")),
}

# Contemporary genre labels build on the broader genre/theme relationships above.
# Keeping those relationships composable also lets a mixed concept be evaluated
# without maintaining another large, brittle compatibility table.
GOOD_MATCHES.update(
    {
        "Battle Royale": GOOD_MATCHES["First-Person Shooter"] | GOOD_MATCHES["Survival Game"],
        "Extraction Shooter": GOOD_MATCHES["First-Person Shooter"] | GOOD_MATCHES["Strategy"],
        "Survivors-like": GOOD_MATCHES["Action"] | GOOD_MATCHES["Skill Game"],
        "Roguelike": GOOD_MATCHES["Role-Playing Game"] | GOOD_MATCHES["Strategy"],
        "Roguelite": GOOD_MATCHES["Action"] | GOOD_MATCHES["Role-Playing Game"],
        "Deckbuilder": GOOD_MATCHES["Strategy"] | GOOD_MATCHES["Puzzle Game"],
        "Automation": GOOD_MATCHES["Building Game"] | GOOD_MATCHES["Economic Simulation"],
        "Cozy Game": GOOD_MATCHES["Simulation"] | GOOD_MATCHES["Visual Novel"],
        "Social Deduction": GOOD_MATCHES["Strategy"] | GOOD_MATCHES["Adventure"],
        "Immersive Sim": GOOD_MATCHES["Simulation"] | GOOD_MATCHES["First-Person Shooter"],
        "Soulslike": GOOD_MATCHES["Action"] | GOOD_MATCHES["Role-Playing Game"],
        "Metroidvania": GOOD_MATCHES["Platformer"] | GOOD_MATCHES["Adventure"],
    }
)

PLATFORMS = [
    ("Tapple I", (1976, 1), (1977, 10), 3300, "PC"), ("Arcade System 500", (1976, 1), (1981, 2), 17000, "Arcade"), ("Fairtech-CF", (1976, 1), (1983, 3), 3300, "Console"),
    ("Astro Arcade", (1977, 1), (1985, 7), 3600, "Console"), ("Commander PETE", (1977, 1), (1982, 12), 3500, "PC"), ("Tapple II", (1977, 6), (1993, 11), 3550, "PC"), ("RRS-80", (1977, 8), (1981, 1), 3500, "PC"), ("Katari 2600", (1977, 9), (1992, 1), 10800, "Console"),
    ("Magma Olympus II", (1978, 12), (1984, 3), 4000, "Console"), ("Rodovin APVS", (1978, 2), (1983, 10), 3900, "Console"), ("Minivision", (1979, 11), (1981, 12), 4500, "Console"), ("Katari 850", (1979, 11), (1992, 1), 4350, "PC"), ("Intelvisual", (1979, 12), (1990, 1), 4250, "Console"),
    ("ZY80", (1980, 1), (1981, 12), 5000, "PC"), ("Commander VEC-20", (1980, 7), (1985, 1), 4900, "PC"), ("Arcade System 800", (1981, 2), (1986, 2), 30000, "Arcade"), ("CassetteView", (1981, 7), (1985, 11), 5600, "Console"), ("Personal Computer", (1981, 8), None, 5500, "PC"),
    ("Intex AD-Vision", (1982, 1), (1983, 10), 6400, "Console"), ("Vector-x", (1982, 11), (1984, 12), 6300, "Console"), ("W-Tech Vision", (1982, 2), (1986, 1), 6000, "Console"), ("ZY Spectre", (1982, 4), (1992, 1), 6000, "PC"), ("Arcade-2640", (1982, 5), (1984, 11), 6000, "Console"),
    ("Coleckovision", (1982, 8), (1985, 10), 6000, "Console"), ("Commander C63", (1982, 8), (1994, 4), 6500, "PC"), ("Katari 5200", (1982, 9), (1984, 9), 6500, "Console"), ("PVX-1000", (1983, 10), (1984, 3), 7100, "Console"), ("W-Tech Laser 2000", (1983, 11), (1985, 7), 6700, "PC"),
    ("Mintendu System", (1983, 7), (1995, 9), 7500, "Console"), ("SIG-2000", (1983, 7), (1985, 10), 7000, "Console"), ("McIntosh", (1984, 1), None, 7000, "PC"), ("Amstar CCP", (1984, 6), (1990, 4), 7100, "PC"), ("Super CassetteView", (1984, 7), (1987, 11), 7200, "Console"),
    ("Commander C127", (1985, 1), (1989, 1), 8700, "PC"), ("Siga Master Deck", (1985, 10), (1996, 10), 8800, "Console"), ("Katari STT", (1985, 6), (1993, 4), 8000, "PC"), ("Amigo 1000", (1985, 7), (1987, 7), 8500, "PC"), ("Arcade System 1000", (1986, 2), (1991, 2), 45000, "Arcade"),
    ("Katari 7800", (1986, 5), (1992, 1), 9000, "Console"), ("Core Engine", (1987, 10), (1994, 12), 10000, "Console"), ("Amigo 500", (1987, 4), (1991, 4), 10500, "PC"), ("Acoon Archimed", (1987, 6), (1995, 7), 10000, "PC"), ("Siga Mega Deck", (1988, 10), (1997, 10), 10500, "Console"),
    ("Katari Lunx", (1989, 10), (1995, 12), 11500, "Handheld"), ("Mintendu Game Portable", (1989, 4), (2003, 3), 11600, "Handheld"), ("Philops CD-X", (1990, 10), (1998, 9), 16600, "Console"), ("Siga Play Gear", (1990, 10), (1997, 3), 16500, "Handheld"), ("Game Mate", (1990, 10), (1994, 3), 16000, "Handheld"),
    ("Super Mintendu System", (1990, 11), (1999, 9), 16100, "Console"), ("Core Engine GT", (1990, 12), (1994, 12), 17000, "Handheld"), ("Commander Game System", (1990, 12), (1992, 12), 16000, "Console"), ("Geo Reo", (1990, 4), (2004, 4), 16600, "Console"), ("Amstar GX3000", (1990, 9), (1991, 12), 16100, "Console"),
    ("Arcade System 1500", (1991, 2), (1995, 2), 72000, "Arcade"), ("Amigo CTV", (1991, 3), (1993, 10), 15500, "Console"), ("Core Engine Duo", (1991, 9), (1995, 12), 18500, "Console"), ("Wasari Megavision", (1992, 11), (1994, 12), 20000, "Handheld"), ("4D-OH", (1993, 10), (1996, 1), 21100, "Console"),
    ("Katari Puma", (1993, 11), (1996, 7), 21000, "Console"), ("PhaserActive", (1993, 4), (1996, 11), 21800, "Console"), ("Amigo CDX-32", (1993, 9), (1994, 4), 21700, "Console"), ("Siga Uranus", (1994, 11), (2000, 11), 23900, "Console"), ("Core-FX", (1994, 12), (1998, 12), 24000, "Console"),
    ("Pony Gamestation", (1994, 12), (2006, 8), 24300, "Console"), ("Play-X", (1994, 9), (1997, 10), 23000, "Console"), ("Mega-A-Can", (1995, 10), (1997, 10), 26900, "Console"), ("Siga Noman", (1995, 10), (1999, 2), 26700, "Handheld"), ("Arcade System 1800", (1995, 2), (2000, 2), 95000, "Arcade"),
    ("Mintendu Virtual Portable", (1995, 7), (1996, 3), 26900, "Handheld"), ("Pippal", (1996, 4), (1997, 12), 28500, "Console"), ("Mintendu 63", (1996, 6), (2002, 4), 28500, "Console"), ("Geo Reo Pocket", (1998, 10), (1999, 12), 33000, "Handheld"), ("Mintendu Game Portable Color", (1998, 10), (2003, 3), 34000, "Handheld"),
    ("Siga Reamcast", (1998, 11), (2001, 12), 31300, "Console"), ("Wonderbird", (1999, 3), (2003, 9), 36700, "Handheld"), ("Arcade System 2000", (2000, 2), (2005, 2), 120000, "Arcade"), ("Pony Gamestation 2", (2000, 3), (2013, 1), 42000, "Console"), ("Minisoft YBox", (2001, 11), (2009, 3), 44500, "Console"),
    ("Game Portable Advance", (2001, 3), (2008, 11), 43000, "Handheld"), ("Mintendu Playcube", (2001, 9), (2007, 3), 44300, "Console"), ("M-Cage", (2003, 10), (2005, 11), 53000, "Mobile"), ("Mintendu D-S", (2004, 11), (2013, 8), 62000, "Handheld"), ("Pony GSP", (2004, 12), (2014, 12), 59500, "Handheld"),
    ("Minisoft YBox 370", (2005, 11), (2016, 4), 78000, "Console"), ("Arcade System 2500", (2005, 2), (2022, 2), 215000, "Arcade"), ("Gizmos", (2005, 3), (2006, 2), 65000, "Handheld"), ("Pony Gamestation 3", (2006, 11), (2017, 5), 75600, "Console"), ("Mintendu Fii", (2006, 11), (2013, 10), 74000, "Console"),
    ("iTapple", (2007, 11), (2012, 11), 5000, "Mobile"), ("Redberry Z5", (2008, 2), (2013, 2), 4800, "Mobile"), ("Sybios 500", (2009, 2), (2014, 2), 4100, "Mobile"), ("Cyboo", (2009, 5), (2011, 9), 93100, "Console"), ("Droidan I", (2009, 6), (2014, 6), 4600, "Mobile"),
    ("iTapple 2", (2011, 11), (2016, 11), 5800, "Mobile"), ("Pony GSViva", (2011, 12), (2019, 3), 100000, "Handheld"), ("Mintendu 3SD", (2011, 2), (2023, 11), 107000, "Handheld"), ("Neo X", (2012, 12), (2020, 1), 113400, "Handheld"), ("Mintendu FiiU", (2012, 12), (2017, 6), 115000, "Console"),
    ("Redberry Z10", (2012, 2), (2017, 2), 5200, "Mobile"), ("Minisoft Phone I", (2012, 9), (2017, 9), 5000, "Mobile"), ("Minisoft YBox 720", (2013, 11), (2023, 5), 124000, "Console"), ("Pony Gamestation 4", (2013, 11), (2022, 6), 124000, "Console"), ("Sybios 800", (2013, 2), (2018, 2), 4600, "Mobile"),
    ("Droidan II", (2013, 6), (2018, 6), 5500, "Mobile"), ("Oya", (2013, 6), (2015, 7), 120000, "Console"), ("Nvideo Pro", (2013, 7), (2022, 10), 120000, "Console"), ("iTapple 3", (2015, 11), (2020, 11), 6900, "Mobile"), ("Beam Machine", (2015, 11), (2021, 2), 133000, "PC"),
    ("Redberry Z20", (2016, 2), (2021, 2), 5900, "Mobile"), ("Fusion F1000", (2016, 6), (2018, 7), 140000, "Console"), ("Minisoft Phone II", (2016, 9), (2021, 9), 5900, "Mobile"), ("Mintendu Zwitch", (2017, 3), (2025, 12), 145000, "Handheld"), ("Droidan III", (2017, 6), (2022, 6), 6200, "Mobile"),
    ("iTapple 4", (2019, 11), (2024, 11), 8000, "Mobile"), ("Pony Gamestation 5", (2020, 11), (2030, 6), 168000, "Console"), ("Minisoft YBox SX", (2020, 11), (2030, 5), 165000, "Console"), ("Katari VCC", (2020, 11), (2025, 11), 79500, "Console"), ("Intelvisual Amikos", (2021, 10), (2026, 2), 115000, "Console"),
    ("Droidan IV", (2021, 6), (2026, 6), 7700, "Mobile"), ("Beam Deck", (2022, 2), (2028, 11), 142000, "Handheld"), ("iTapple 5", (2023, 11), None, 8400, "Mobile"), ("Commander Game System II", (2023, 12), None, 185000, "Console"), ("Mintendu Zwitch Pro", (2024, 12), (2031, 1), 175000, "Handheld"),
    ("Asia Box", (2024, 2), None, 190000, "Console"), ("Siga Play Gear II", (2025, 11), None, 182000, "Handheld"), ("Mintendu 3DEX", (2025, 2), None, 178000, "Handheld"), ("Siga MegaCast", (2025, 4), None, 203000, "Console"), ("Droidan V", (2025, 6), None, 8000, "Mobile"),
    ("Katari Puma 2", (2026, 7), None, 206000, "Console"), ("Minisoft YBox SX-II", (2028, 11), None, 224000, "Console"), ("Pony Gamestation 6", (2028, 12), None, 228000, "Console"), ("Mintendu MX", (2030, 1), None, 217000, "Console"),
]

PLATFORM_PROFILES = {
    "PC": {
        "audiences": ["Adults", "Seniors"],
        "genres": {"Strategy", "Real-Time Strategy", "Role-Playing Game", "Simulation", "Economic Simulation", "Building Game", "Adventure", "Visual Novel"},
        "topics": {"Ancient", "Cyberpunk", "Dungeons", "Economy", "Fantasy", "Game Development", "Historical", "Magic", "Middle Ages", "Politics", "Science", "Space", "World Wars"},
    },
    "Console": {
        "audiences": ["Children", "Teenagers", "Adults"],
        "genres": {"Action", "Platformer", "Racing", "Sports Game", "Fighting Game", "Third-Person Shooter", "First-Person Shooter"},
        "topics": {"Aliens", "Cars", "Dinosaurs", "Kart Racing", "Motorcycles", "Ninjas", "Robots", "Space", "Sports", "Superheroes", "World Wars", "Zombies"},
    },
    "Handheld": {
        "audiences": ["Children", "Teenagers"],
        "genres": {"Puzzle Game", "Skill Game", "Platformer", "Racing", "Sports Game", "Visual Novel"},
        "topics": {"Animals", "Candy", "Cats", "Cooking", "Dogs", "Kids", "Music", "Pets", "Puzzles", "School", "Sports", "Toys", "Zoo"},
    },
    "Arcade": {
        "audiences": ["Children", "Teenagers", "Adults"],
        "genres": {"Action", "Racing", "Sports Game", "Skill Game", "Fighting Game"},
        "topics": {"Airplanes", "Boxing", "Cars", "Karate", "Kart Racing", "Kung Fu", "Motorcycles", "Ninjas", "Sports", "Wrestling"},
    },
    "Mobile": {
        "audiences": ["Children", "Teenagers", "Adults", "Seniors"],
        "genres": {"Puzzle Game", "Skill Game", "Simulation", "Visual Novel", "Economic Simulation"},
        "topics": {"Animals", "Candy", "Cooking", "Dating", "Education", "Everyday Life", "Fitness", "Music", "Pets", "Photography", "Puzzles", "School", "Toys"},
    },
}
